# permissions for end users to edit statics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: static-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: static-webpage-k8s-operator
    app.kubernetes.io/part-of: static-webpage-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: static-editor-role
rules:
- apiGroups:
  - webpage.daemon.io
  resources:
  - statics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webpage.daemon.io
  resources:
  - statics/status
  verbs:
  - get
