apiVersion: webpage.daemon.io/v1alpha1
kind: Static
metadata:
  name: static-sample
spec:
  branch: "master"
  repository: "https://github.com/kubernetes/git-sync"
  wait: 180
  ingress:
    annotation:
      kubernetes.io/ingress.class: nginx
    host:
      - "page.example.com"
    tls: true
